packages <- c("magrittr", "devtools")
lapply(packages, function(x) library(x, character.only = T))
cat(paste(packages, collapse = ", "), " packages were loaded.")
load_all()
options(error = NULL)
