# Wed May 13 18:47:48 2020 ------------------------------
# Bug: Subsetting the output of tx_reads() in a non-continuous manner
# causes problems when binding the data.tables generated by the hlp_coverageTab
# function.
# Fix: Changing an lapply iterate for the names of the genes in list
#---
# date() ------------------------------
# Bug:
# Fix:
#---
# date() ------------------------------
# Bug:
# Fix:
#---
