# Wed May 13 18:47:48 2020 ------------------------------
# Bug: Subsetting the output of tx_reads() in a non-continuous manner
# causes problems when binding the data.tables generated by the hlp_coverageTab
# function.
# Fix: Changing an lapply iterate for the names of the genes in list
#---
# Tue Dec 22 13:55:03 2020 ------------------------------
# Bug: tx_add_refSeqDT() couldn't deal with geneAnnots with only one exon genes.
# Fix: if_IRangesList_Unlist(), unlists only if blocks are in a list.
#---
# date() ------------------------------
# Bug:
# Fix:
#---
